### ISSUE TITLE
Cannot use uri encoded string in username

### ISSUE THREAD

**Issue by mharrington622** [npm/npm-user-validate#12]
This is a scenario being encountered in a private npm registry.

If your username is, for example, "me@github.com", then the non-url-safe error is thrown as expected.  If you try to encode this yourself as "me%40github.com" the check just compares "me%40github.com" against "me%2540github.com" which fails unexpectedly.  Anything beyond this would obviously be an infinite loop to nowhere.

A solution to solve this use case would be to decode the username before encoding it and then comparing the value.  Can anyone think of any values that would not legitimately validate or that would unexpectedly pass using this solution?

**Comment by jlambert121** [comment]
I was looking at this this morning and testing your suggestion.  That correctly gets past the check itself, but fails on the couch login (I know nothing of the various login methods that could or are supported) because of https://github.com/npm/npm-profile/blob/latest/lib/index.js#L148.  

`npm ERR! Registry returned 401 for PUT on https://host/repo/-/user/org.couchdb.user:me%2540github.com`

For my amusement, I removed the username check in npm-user-validate and was able to successfully log in (entering my username as me@github.com) because it is escaped later at the link above.

**Comment by isaacs** [comment]
https://github.com/npm/npm-user-validate/pull/13#issuecomment-590641822
